# Generated by Django 4.2.1 on 2023-05-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pivo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("setting", models.BooleanField(default=False)),
            ],
        ),
    ]
