# Generated by Django 4.2.1 on 2023-06-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pivo", "0002_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="tap",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tap",
            name="volume",
            field=models.IntegerField(default=30),
        ),
    ]
