# Generated by Django 4.2.1 on 2023-06-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivo', '0003_tap_price_tap_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tap',
            name='volume',
            field=models.IntegerField(default=50),
        ),
    ]
