# Generated by Django 5.1.6 on 2025-02-28 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pivo", "0004_alter_tap_volume"),
    ]

    operations = [
        migrations.RenameField(
            model_name="settings",
            old_name="setting",
            new_name="is_enabled",
        ),
        migrations.RenameField(
            model_name="tap",
            old_name="tap",
            new_name="is_tapped",
        ),
        migrations.AlterField(
            model_name="beer",
            name="brewery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pivo.brewery"
            ),
        ),
        migrations.AlterField(
            model_name="tap",
            name="beer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pivo.beer"
            ),
        ),
    ]
