# Generated by Django 5.1.6 on 2025-02-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pivo", "0005_rename_setting_settings_is_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="homepage_images")),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
